db.Personas.insertMany([

    {Nombre: "Fernando",
    Apellidos: "Galvez",
    Publicaciones: 150,
    NombresUsuarios: ["FG", "FerGal"],
    NumPublicaciones: { Fotos: 55, Videos: 45, Frases: 50},
    HorasDeUso: 6,
    FechaIngreso: new Date(2008,9,21),
    Direccion: "Calle Nueva York",
    CodPost: 41012,
    Telefono: 665665987,
    CodRedSS: [2, 3]},

    {Nombre: "Maria",
    Apellidos: "Fernandez",
    Publicaciones: 3,
    NombresUsuarios: ["MF", "MarFer"],
    NumPublicaciones: { Fotos: 1, Videos: 1, Frases: 1},
    HorasDeUso: 6,
    FechaIngreso: new Date(2012,1,1),
    CodPost: 41012,
    CodRedSS: [1, 2, 3]},

    {Nombre: "Gonzalo",
    Apellidos: "Marin",
    Publicaciones: 23,
    NombresUsuarios: ["GM", "GonMar"],
    NumPublicaciones: { Fotos: 20, Frases: 3},
    HorasDeUso: 4, 
    FechaIngreso: new Date(2020,5,3),
    CodRedSS: 4,
    CodPost:41013 },
    

    {Nombre: "Rafael",
    Apellidos: "Gallardo",
    NombresUsuarios: ["RG", "RafGal"],
    HorasDeUso: 2,
    FechaIngreso: new Date(2019,12,23),
    Direccion: "Calle Permaldo",
    CodPost: 41013,
    CodRedSS: [5, 2]   },

    {Nombre: "Berta",
    Apellidos: "Tomares",
    Publicaciones: 5,
    NombresUsuarios: ["BT", "BerTom"],
    NumPublicaciones: { Videos: 3 , Frases: 2 },
    HorasDeUso: 2,
    FechaIngreso: new Date(2015,6,30),
    CodPost: 41015,
    Telefono: 695665265,
    CodRedSS: 1},

    {Nombre: "Tomas",
    Apellidos: "Gutierrez",
    Publicaciones: 120,
    NombresUsuarios: ["TG", "TomGut"],
    NumPublicaciones: { Frases:120 },
    HorasDeUso: 4,
    FechaIngreso: new Date(2009,3,5),
    CodRedSS: [1, 2, 3, 4, 5],
    CodPost:41015 },

    {Nombre: "Lucia",
    Apellidos: "Garcia",
    NombresUsuarios: ["LG", "LucGar"],
    HorasDeUso: 1,
    FechaIngreso: new Date(2020,1,1),
    Direccion: "Calle Manteca",
    CodPost: 51020,
    Telefono: 669875665,
    CodRedSS: 4},

    {Nombre: "Ignacio",
    Apellidos: "Mora",
    NombresUsuarios: ["IM", "IgnMor"],
    FechaIngreso: new Date(2015,3,23),
    CodRedSS: [1, 2],
    CodPost:51020},

    {Nombre: "Marta",
    Apellidos: "Martinez",
    Publicaciones: 28,
    NombresUsuarios: ["MM", "MarMar"],
    NumPublicaciones: { Fotos:8 , Videos:19 , Frases:1 },
    HorasDeUso: 5,
    FechaIngreso: new Date(2013,9,9),
    CodRedSS: [3, 4, 5],
    CodPost:51032},

    {Nombre: "Carlos",
    Apellidos: "Martinez",
    NombresUsuarios: ["CM", "CarMar"],
    FechaIngreso: new Date(2017,6,16),
    Direccion: "Calle Benidorm",
    CodPost: 51032,
    Telefono: 665665665,
    CodRedSS: [1, 5]},

    {Nombre: "Carlos",
    Apellidos: "Gutierrez",
    Publicaciones: 120,
    NombresUsuarios: ["CG", "CarGut"],
    NumPublicaciones: { Videos:20 , Frases:100 },
    HorasDeUso: 5,
    FechaIngreso: new Date(2012,4,12),
    CodPost: 91091,
    Direccion:"Calle Bambino",
    CodRedSS: 5},

    {Nombre: "Alicia",
    Apellidos: "Lorenzo",
    Publicaciones: 76,
    NombresUsuarios: ["AL", "AliLor"],
    NumPublicaciones: { Fotos:70 , Frases:6 },
    HorasDeUso: 4,
    FechaIngreso: new Date(2018,9,9),
    CodRedSS: [2, 3, 4, 5],
    CodPost:91091},

    {Nombre: "Roberto",
    Apellidos: "Madrid",
    Publicaciones: 12,
    NombresUsuarios: ["RM", "RobMad"],
    NumPublicaciones: { Fotos:2 , Videos:2 , Frases:8 },
    HorasDeUso: 6,
    FechaIngreso: new Date(2013,10,2),
    CodRedSS: [1, 2],
    CodPost:91043 },

    {Nombre: "Martina",
    Apellidos: "Suarez",
    NombresUsuarios: ["", ""],
    FechaIngreso: new Date(2020,12,1),
    Telefono: 666789987,
    CodRedSS: 1,
    CodPost:91043},

    {Nombre: "Blanca",
    Apellidos: "Suarez",
    Publicaciones: 25,
    NombresUsuarios: ["BS", "BlaSua"],
    NumPublicaciones: { Fotos: 5, Videos: 20 },
    HorasDeUso: 2,
    FechaIngreso: new Date(2015,10,10),
    Direccion: "Calle Primera",
    CodPost:34376,
    CodRedSS: [2, 3, 4]},

    {Nombre: "Miguel",
    Apellidos: "Ramos",
    NombresUsuarios: ["MR", "MigRam"],
    FechaIngreso: new Date(2009,4,12),
    CodRedSS: [1, 2],
    CodPost:34376},

    {Nombre: "Paula",
    Apellidos: "Ramos",
    Publicaciones: 170,
    NombresUsuarios: ["PR", "PauRam"],
    NumPublicaciones: { Frases: 170 },
    HorasDeUso: 4,
    FechaIngreso: new Date(2013,3,21),
    CodRedSS: 4,
    CodPost:34352},

    {Nombre: "Fernanda",
    Apellidos: "Montero",
    Publicaciones: 12,
    NombresUsuarios: ["FM", "FerMon"],
    NumPublicaciones: { Fotos: 2, Videos: 10 },
    HorasDeUso: 1,
    FechaIngreso: new Date(2018,2,28),
    Direccion: "Calle Betis",
    CodRedSS: 1,
    CodPost:34352},

    {Nombre: "Fernando",
    Apellidos: "Romero",
    Publicaciones: 23,
    NombresUsuarios: ["FR", "FerRom"],
    NumPublicaciones: { Fotos: 21, Videos: 1, Frases: 1 },
    HorasDeUso: 2,
    FechaIngreso: new Date(2010,12,1),
    CodRedSS: 2,
    CodPost:22781},

    {Nombre: "Juan",
    Apellidos: "Sanchez",
    Publicaciones: 1,
    NombresUsuarios: ["JS", "JuaSan"],
    NumPublicaciones: { Videos:1 },
    HorasDeUso: 2,
    FechaIngreso: new Date(2020,11,20),
    Telefono:182787872,
    CodPost:22781,
    CodRedSS: 4},

    {Nombre: "Pedro",
    Apellidos: "Juarez",
    Publicaciones: 10,
    NombresUsuarios: ["PJ", "PedJua"],
    NumPublicaciones: { Fotos: 1, Videos: 1, Frases: 8 },
    HorasDeUso: 7,
    FechaIngreso: new Date(2010,11,20),
    CodPost:41015,
    CodRedSS: 5},

    {Nombre: "Domingo",
    Apellidos: "Dominguez",
    Publicaciones: 150,
    NombresUsuarios: ["DD", "DomDom"],
    NumPublicaciones: { Fotos: 50, Videos: 100 },
    HorasDeUso: 7,
    FechaIngreso: new Date(2010,1,2),
    CodRedSS: 4,
    CodPost:22754},

    {Nombre: "Angeles",
    Apellidos: "Suarez",
    Publicaciones: 70,
    NombresUsuarios: ["AS", "AngSua"],
    NumPublicaciones: { Fotos: 29, Videos: 40, Frases: 1 },
    FechaIngreso: new Date(2010,11,20),
    Direccion: "Calle Reinos",
    CodRedSS: [2, 5, 4],
    CodPost:22754},

    {Nombre: "Aurora",
    Apellidos: "Juarez",
    Publicaciones: 1,
    NombresUsuarios: ["AJ", "AurJua"],
    NumPublicaciones: { Fotos: 1 },
    HorasDeUso: 7,
    FechaIngreso: new Date(2012,12,10),
    CodRedSS: [1, 3],
    CodPost:11034},

    {Nombre: "Tomas",
    Apellidos: "Marquez",
    Publicaciones: 25,
    NombresUsuarios: ["TM", "TomMar"],
    NumPublicaciones: { Fotos: 10, Videos: 10, Frases: 5 },
    HorasDeUso: 7,
    FechaIngreso: new Date(2007,7,1),
    CodRedSS: [4, 5],
    CodPost:11034},

    {Nombre: "Jeronimo",
    Apellidos: "Martin",
    Publicaciones: 4,
    NombresUsuarios: ["JM", "JerMar"],
    NumPublicaciones: { Fotos: 1, Videos: 1, Frases: 2 },
    HorasDeUso: 3,
    FechaIngreso: new Date(2017,1,20),
    CodPost: 11034,
    CodRedSS: [1, 2, 3, 4, 5]},

    {Nombre: "Antonio",
    Apellidos: "Romero",
    NombresUsuarios: ["AR", "AntRom"],
    FechaIngreso: new Date(2020,5,3),
    Direccion: "Calle Madrid",
    Telefono: 783893094,
    CodPost: 11027,
    CodRedSS: [2, 3, 4, 5]},

    {Nombre: "Patricia",
    Apellidos: "Velez",
    Publicaciones: 568,
    NombresUsuarios: ["PV", "PatVel"],
    NumPublicaciones: { Fotos: 500, Videos: 60, Frases: 8 },
    HorasDeUso: 2,
    FechaIngreso: new Date(2020,1,30),
    Direccion: "Calle Cuenca",
    CodRedSS: [3, 2],
    CodPost:11027},

    {Nombre: "Adrian",
    Apellidos: "Quevedo",
    Publicaciones: 1034,
    NombresUsuarios: ["AQ", "AdrQue"],
    NumPublicaciones: { Fotos: 504, Videos: 30, Frases: 500 },
    HorasDeUso: 5,
    FechaIngreso: new Date(2010,1,1),
    CodRedSS: [3, 5],
    CodPost:11027},

    {Nombre: "David",
    Apellidos: "Parejo",
    Publicaciones: 10,
    NombresUsuarios: ["DP", "DavPar"],
    NumPublicaciones: { Fotos: 10 },
    HorasDeUso: 3,
    FechaIngreso: new Date(2013,9,9),
    Telefono: 657849499,
    CodRedSS: [1, 3, 5],
    CodPost:91043},

    {Nombre: "Pedro",
    Apellidos: "Sanchez",
    Publicaciones: 45,
    NombresUsuarios: ["PS", "PedSan"],
    NumPublicaciones: { Fotos: 5, Videos: 20, Frases: 20 },
    HorasDeUso: 4,
    FechaIngreso: new Date(2018,11,30),
    CodRedSS: 4,
    CodPost:41012},

]);